language: python

python:
  - "2.6"
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcairo2-dev libpango1.0-dev libglib2.0-dev libxml2-dev librrd-dev

install:
  - pip install pip wheel -U
  - pip install .

script: python setup.py test

branches:
  only:
    - master
