language: python

python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

env:
  - TOXENV=py27-tornado2
  - TOXENV=docs

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcairo2-dev libpango1.0-dev libglib2.0-dev libxml2-dev librrd-dev

install:
  - pip install tox pip wheel codecov -U

script:
  - tox

after_success:
  - codecov -e TOX_ENV

branches:
  only:
    - master
